package servlet;

import dto.UserRegisterDTO;
import exception.EmailAlreadyExistsException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import service.CategoryService;
import service.UserService;

import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;

@WebServlet("/register")
public class RegisterServlet extends HttpServlet {

    private final UserService userService;
    private final CategoryService categoryService;

    public RegisterServlet() {
        this(new UserService(), new CategoryService());
    }

    RegisterServlet(UserService userService, CategoryService categoryService) {
        this.userService = userService;
        this.categoryService = categoryService;
    }
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        HttpSession session = req.getSession();
        if(session !=null && session.getAttribute("user")!=null ) {
            resp.sendRedirect("home");
            return;
        }
        req.setAttribute("categories", categoryService.getAll());
        req.getRequestDispatcher("/WEB-INF/register.jsp").forward(req,resp);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {

        req.setCharacterEncoding("UTF-8");

        String fullName        = req.getParameter("fullName");
        String email           = req.getParameter("email");
        String password        = req.getParameter("password");
        String gender          = req.getParameter("gender");
        String dobStr          = req.getParameter("dob");
        String jobTitle        = req.getParameter("jobTitle");
        String shippingAddress = req.getParameter("shippingAddress");
        String creditLimitStr  = req.getParameter("creditLimit");
        String[] styleInterests = req.getParameterValues("styleInterests");

        if (isEmpty(fullName) || isEmpty(email) || isEmpty(password) || isEmpty(gender)) {
            forwardWithError(req, resp, "Please fill in all required fields.");
            return;
        }
        if (password.length() < 8) {
            forwardWithError(req, resp, "Password must be at least 8 characters.");
            return;
        }

        LocalDate birthday = null;
        if (!isEmpty(dobStr)) {
            try {
                DateTimeFormatter fmt = DateTimeFormatter.ofPattern("MM/dd/yyyy");
                birthday = LocalDate.parse(dobStr, fmt);
            } catch (DateTimeParseException e) {
                forwardWithError(req, resp, "Invalid date of birth format.");
                return;
            }
        }

        BigDecimal creditLimit;
        try {
            creditLimit = new BigDecimal(creditLimitStr);
            if (creditLimit.compareTo(BigDecimal.ZERO) < 0 ||
                    creditLimit.compareTo(new BigDecimal("999999")) > 0) {
                forwardWithError(req, resp, "Credit limit must be between 0 and 999,999.");
                return;
            }
        } catch (NumberFormatException e) {
            creditLimit = BigDecimal.ZERO;
        }

        List<Integer> interestIds = new ArrayList<>();
        if (styleInterests != null) {
            for (String id : styleInterests) {
                try {
                    interestIds.add(Integer.parseInt(id));
                } catch (NumberFormatException ignored) {}
            }
        }

        UserRegisterDTO dto = new UserRegisterDTO(
                null,                                               // id — generated by DB
                fullName.trim(),                                    // name
                email.trim().toLowerCase(),                         // email
                password,                                           // passwordHash — hashed in service
                gender,                                             // gender
                birthday,                                           // birthday
                jobTitle != null ? jobTitle.trim() : null,          // job
                shippingAddress != null ? shippingAddress.trim() : null, // address
                creditLimit,                                        // creditLimit
                interestIds                                         // interests
        );

        try {
            userService.register(dto);
            resp.sendRedirect(req.getContextPath() +
                    "/login?successMsg=Account+created+successfully.+Please+sign+in.");

        } catch (EmailAlreadyExistsException e) {
            forwardWithError(req, resp, "An account with this email already exists.");

        } catch (Exception e) {
            forwardWithError(req, resp, "Something went wrong. Please try again.");
        }
    }
    private boolean isEmpty(String val) {
        return val == null || val.trim().isEmpty();
    }
    private void forwardWithError(HttpServletRequest req, HttpServletResponse resp, String message)
            throws ServletException, IOException {
        req.setAttribute("errorMsg", message);
        req.setAttribute("categories", categoryService.getAll());
        req.getRequestDispatcher("/WEB-INF/register.jsp").forward(req, resp);
    }
}
